### ISSUE TITLE
investigate and propose a specific messaging technology

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-general-issues#17]
the technologies mentioned include: ActiveMQ, Kafka, Microsoft Azure Messaging Service

Please make a recommendation based on known restrictions/conditions of JHU and Data Archive specific infrastructure.

part of ticket #13

**Comment by jhujasonw** [comment]
Further progress has been made on #13 that may remove any restrictions on what messaging queue system we would need to use.  

There was a limitation that public servers would not have access to a private ActiveMQ/Kafka server running in the cloud (due to limitations on what can and cannot access things on the JHU Private Cloud Virtual Network)  With the infrastructure @derekbelrose came up with last week, that limitation may be lifted.  

Can I suggest parking this for the moment until that infrastructure piece is hashed out?

**Comment by jhujasonw** [comment]
There was also some discussion on slack about whether or not the deposit UI needed to be public or if it could remain internal to the Hopkins network.  I believe that if it was internal to the Hopkins network, there is less of a technical impact on this choice.  If a decision is made about the disposition of the deposit UI and where it can/need to reside, that will impact any further investigation into this.

**Comment by jhujasonw** [comment]
Last Wednesday, the event fabric was discussed and it was ratified that we would use ActiveMQ for MVP of JHUDA.  Closing this ticket.
