### ISSUE TITLE
propose how to allow DA UI to communicate with the message bus

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-general-issues#18]
Part of issue #13 

There are 2 UIs to consider: 
- End User UI, which is publicly accessible after JHED authentication 
- The HB UI, which is needs to be secured enough to allow HB to securely access deposited content that might contain PHI and PII.

**Comment by jhujasonw** [comment]
I believe at a previous discussion, it was agreed that the whole JHUDA would reside behind the JHU firewall.  I believe that this would mean that the UI could talk directly to fedora, which means that this ticket is pretty much resolved I believe.  I am not closing it, in case my understanding is wrong.  I am commenting on it because it mentioned #13.

**Comment by htpvu** [comment]
This ticket is deprecated. the topic of concerned is covered as part of the JHUDA architecture and eventing discussions.
