### ISSUE TITLE
Investigate Dataverse SWORD v2 endpoints

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-general-issues#24]
[[#LAG-2936] Dataverse questions from Hanh.pdf](https://github.com/jhu-sheridan-libraries/slarx-general-issues/files/3757127/LAG-2936.Dataverse.questions.from.Hanh.pdf)

information relating to Dataverse known to us can be found in the attached image. additional questions can be routed to Mark Cyzyk. Please CC me in such communication.

**Comment by emetsger** [comment]
A general document that outlines the investigation and implementation tasks specific to the Dataverse implementation lives [here](https://docs.google.com/document/d/17-r_rnLTePbi-bGXBZg0RQM3v765BtB7UW0i9b_e0II/edit?usp=sharing).

**Comment by emetsger** [comment]
[LAG-3018](https://issues.library.jhu.edu/browse/LAG-3018) has been opened which tracks access to Dataverse and its metadata requirements

**Comment by emetsger** [comment]
[LAG-3018](https://issues.library.jhu.edu/browse/LAG-3018) has been closed.  I have access to the stage dataverse for testing, and have minimal metadata requirements for the SWORD endpoint, and the JHU DA metadata reqs [here](https://docs.google.com/spreadsheets/d/1eweWbg45kUVh1Wvvjz2nPLngj8PUKEwWdzOjGALGnXs/edit?ouid=117619527213185663034&usp=sheets_home&ths=true).

My preliminary investigation and Dataverse documentation indicate that Dataverse SWORD deposit is a two-step process: 1) submit the metadata, 2) submit the user content (as a zip).  Currently I'm verifying that this is the case by looking at the source code.

The review of the source code would conclude the work for this issue (i.e. complete the investigation of the Dataverse SWORD v2 endpoints).

Assuming that the review of the source code confirms the documented and observed behavior (i.e. that deposit is a two-step process), then that will impact the scope of [updating core deposit services](https://github.com/jhu-sheridan-libraries/jhuda-deposit-service/issues/2).  The [implementation doc](https://docs.google.com/document/d/17-r_rnLTePbi-bGXBZg0RQM3v765BtB7UW0i9b_e0II/edit?usp=sharing) will be fleshed out with consequences.

**Comment by emetsger** [comment]
Preliminary investigation is complete.

SWORD submission to DVN will need to occur as a three step process:
1. POST an Atom Entry containing the package metadata (to the SWORD COL-IRI).
2. POST a zip file containing the user's content using the SimpleZip packaging (to the SWORD EM-IRI)
3. POST a zero-length entity body to the SWORD SE-IRI with the In-Progress header to false to publish the dataset.

(An open question is the degree to which metadata is supported by SWORD ingest.)

This three-step process is incompatible with the current architecture of Deposit Services, where a package and metadata are assembled together, and sent in a single transaction (i.e. a single SWORD API call containing both the package metadata and content, instead of two separate SWORD API calls).  So there are a couple of options:
1.  Implement deposit to Dataverse separate and distinct from Deposit Services, e.g. as it's own service.
    1. This would be incurring technical debt if we wanted to add Dataverse as a supported repository platform for PASS, or if we wanted to use Deposit Services later with the Data Archive (i.e. incorporating it after the MVP)
    1. This is probably the fastest option, because Deposit Services would not be used in the MVP.
1. Update Deposit Services to support this three-step deposit
    1. I can come up with a design and we can decide if it is worth implementing
1. Investigate the Dataverse so-called "native" APIs, and see if that allows for the submission of a single package (containing metadata) in one step.  This seems unlikely, since it would be allowed via SWORD if supported.

**Comment by emetsger** [comment]
For completeness, this [issue](https://github.com/IQSS/dataverse/issues/723) indicates there is no planned support in Dataverse for incorporating metadata in the uploaded zip.
